// 集团军级红蓝对抗动态编组系统 v0.1.0
// 说明：结构按公开信息做游戏化抽象，不对应任何现实部队番号、部署或实时战备数据。
import { ModernBrigadeSystem } from './ModernBrigadeSystem.js';

const TYPE_NAMES={heavy:'重型合成旅',medium:'中型合成旅',light:'轻型合成旅',mountain:'山地合成旅',amphibious:'两栖合成旅'};
const SIDE_NAME={RED:'红方',BLUE:'蓝方'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

function unit(id,name,faction,type,echelon,q,r,manpower,attack,defense,movement,range,equipmentName,qty,parentHQ,formation){
 return {id,name:`${name}｜${equipmentName}`,fullName:name,faction,type,echelon,q,r,strength:100,maxStrength:100,
  manpower,maxManpower:manpower,attack,defense,movement,movementPoints:movement,maxMovementPoints:movement,
  actionPoints:4,maxActionPoints:4,range,morale:85,ammo:100,fuel:100,repairParts:30,supply:100,parentHQ,formation,
  movementClass:['artillery','engineer'].includes(type)?'tracked':(type==='special_forces'?'foot':'wheeled'),
  autoGenerated:true,generatedBy:'GroupArmySystem',equipment:[{type:equipmentName,name:equipmentName,initial:qty,operational:qty,damaged:0,destroyed:0}],
  equipmentSummary:`${equipmentName} ${qty}/${qty}`,modern:{c2:100,intelLevel:0,supply:100,ammo:100,fuel:100,parentHQ}};
}

function relocateBrigade(units, side, brigadeIndex, brigadeType, W,H){
 const left=side==='RED';
 const laneR=[8,19,31,42][brigadeIndex] ?? (8+brigadeIndex*10);
 const targetQ=left?14:W-15;
 const sourceHQ=units.find(u=>u.echelon==='brigade');
 const dq=targetQ-(sourceHQ?.q??targetQ), dr=laneR-(sourceHQ?.r??laneR);
 const oldPrefix=side+'_'; const newPrefix=`${side}_BDE${brigadeIndex+1}_`;
 const idMap=new Map();
 for(const u of units){const old=u.id;u.id=newPrefix+old.replace(oldPrefix,'');idMap.set(old,u.id);}
 for(const u of units){
   if(u.parentHQ&&idMap.has(u.parentHQ))u.parentHQ=idMap.get(u.parentHQ);
   u.q=clamp(u.q+dq,2,W-3);u.r=clamp(u.r+dr,2,H-3);
   u.formation=`${SIDE_NAME[side]}第${brigadeIndex+1}${TYPE_NAMES[brigadeType]??'合成旅'}${u.echelon==='brigade'?'':('·'+(u.formation??''))}`;
   u.brigadeIndex=brigadeIndex+1;u.brigadeType=brigadeType;
   if(u.echelon==='brigade')u.fullName=`${SIDE_NAME[side]}第${brigadeIndex+1}${TYPE_NAMES[brigadeType]}`;
 }
 return units;
}

function armyDirect(side,W,H){
 const left=side==='RED', rearQ=left?4:W-5, dir=left?1:-1, mid=Math.round(H/2), s=SIDE_NAME[side];
 const hq=`${side}_GA_HQ`, form=`${s}集团军直属`;
 const a=[
  unit(hq,`${s}集团军指挥所`,side,'headquarters','army',rearQ,mid,260,2,15,3,1,'集团军野战指挥系统',12,null,form),
  unit(`${side}_GA_C2`,`${s}集团军直属通信指挥分队`,side,'headquarters','battalion',rearQ+dir*2,mid-3,120,2,9,4,1,'野战通信指挥车',10,hq,form),
  unit(`${side}_GA_RECON`,`${s}集团军直属侦察情报分队`,side,'recon','battalion',rearQ+dir*5,mid-7,150,5,7,7,5,'战役侦察无人机系统',12,hq,form),
  unit(`${side}_GA_ART1`,`${s}集团军炮兵旅远程火力营`,side,'artillery','battalion',rearQ+dir*5,mid-10,180,16,6,4,8,'远程火箭炮系统',12,hq,form),
  unit(`${side}_GA_ART2`,`${s}集团军炮兵旅自行火炮营`,side,'artillery','battalion',rearQ+dir*5,mid+10,180,14,7,4,7,'自行榴弹炮系统',18,hq,form),
  unit(`${side}_GA_AD`,`${s}集团军防空旅防空营`,side,'air_defense','battalion',rearQ+dir*3,mid-7,180,9,9,5,6,'野战防空系统',12,hq,form),
  unit(`${side}_GA_AVN`,`${s}集团军陆航旅支援群`,side,'support','battalion',rearQ+dir*2,mid+7,190,11,7,8,6,'武装/运输直升机群',16,hq,form),
  unit(`${side}_GA_SOF`,`${s}集团军特战旅任务分队`,side,'special_forces','company',rearQ+dir*7,mid,70,10,8,8,3,'特战多域任务套件',8,hq,form),
  unit(`${side}_GA_ENG`,`${s}集团军直属工程保障营`,side,'engineer','battalion',rearQ+dir*3,mid+4,190,4,9,4,1,'重型工程保障车辆',16,hq,form),
  unit(`${side}_GA_LOG`,`${s}集团军勤务保障力量`,side,'supply','battalion',rearQ+dir,mid+4,260,2,9,4,1,'综合补给运输车辆',30,hq,form),
  unit(`${side}_GA_REC`,`${s}集团军装备抢修营`,side,'support','battalion',rearQ+dir,mid-4,180,2,10,4,1,'重型装甲抢修车',12,hq,form),
  unit(`${side}_GA_MED`,`${s}集团军卫勤保障分队`,side,'support','battalion',rearQ+dir,mid+8,150,1,8,4,1,'野战医疗保障车辆',12,hq,form)
 ];
 const av=a.find(x=>x.id.endsWith('_AVN'));av.airSupportProvider=true;av.helicopterDeck=['直-10武装直升机','直-19武装侦察直升机','直-20战术通用直升机'];
 const sof=a.find(x=>x.id.endsWith('_SOF'));sof.airDroppable=true;sof.reconRadius=7;sof.stealth=3;sof.multiDomain=true;
 const log=a.find(x=>x.id.endsWith('_LOG'));log.logisticsProvider=true;log.logisticsRadius=8;
 const rec=a.find(x=>x.id.endsWith('_REC'));rec.logisticsProvider=true;rec.repairLevel=4;rec.logisticsRadius=6;rec.recoveryVehicle=true;
 const med=a.find(x=>x.id.endsWith('_MED'));med.medicalCapacity=30;med.logisticsRadius=6;
 return a;
}

function attachHierarchy(units,side){
 const armyHQ=`${side}_GA_HQ`;
 for(const u of units){
  if(u.echelon==='brigade'){u.parentHQ=armyHQ;u.commandLevel='旅';}
  else if(u.echelon==='battalion'){u.commandLevel='营';}
  else if(u.echelon==='company'){u.commandLevel='连';}
  else if(u.echelon==='team'){u.commandLevel='小队';}
 }
}

function deconflict(units,W,H){
 const used=new Set();
 for(const u of units){let q=clamp(Math.round(u.q),1,W-2),r=clamp(Math.round(u.r),1,H-2);let k=`${q},${r}`;
  if(used.has(k)){outer:for(let rad=1;rad<12;rad++)for(let dr=-rad;dr<=rad;dr++)for(let dq=-rad;dq<=rad;dq++){const nq=q+dq,nr=r+dr,nk=`${nq},${nr}`;if(nq>0&&nr>0&&nq<W-1&&nr<H-1&&!used.has(nk)){q=nq;r=nr;k=nk;break outer;}}}
  u.q=q;u.r=r;used.add(k);
 }
 return units;
}

export class GroupArmySystem{
 static isGroupArmy(config){return config?.groupArmySelection===true;}
 static getSelection(){try{return JSON.parse(sessionStorage.getItem('groupArmySelection')||'{}');}catch{return {};}}
 static generate(config){
  const W=Number(config?.trainingMap?.width??76),H=Number(config?.trainingMap?.height??52),sel=this.getSelection();
  const defaults={red:['heavy','heavy','medium','light'],blue:['heavy','medium','medium','mountain']};
  const out=[];
  for(const side of ['RED','BLUE']){
   const key=side.toLowerCase(), types=(sel[key]?.length?sel[key]:defaults[key]).slice(0,4);
   out.push(...armyDirect(side,W,H));
   types.forEach((type,i)=>{
    // 复用已经验证过的合成旅生成器，再重定位并挂入集团军指挥链。
    sessionStorage.setItem('modernBrigadeSelection',JSON.stringify({red:type,blue:type}));
    const pair=ModernBrigadeSystem.generate({...config,groupArmySelection:false,modernBrigadeSelection:true});
    const own=pair.filter(u=>u.faction===side);
    out.push(...relocateBrigade(own,side,i,type,W,H));
   });
   attachHierarchy(out.filter(u=>u.faction===side),side);
  }
  return deconflict(out,W,H);
 }
 static templateInfo(){return TYPE_NAMES;}
}
